[package]
name = "randomx"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = { version = "0.8.4", features = ["hazmat"] }
argon2 = "0.6.0"
cpu-time = "1.0.0"
hex = "0.4.3"
randomx-rs = "1.6.0"

[dev-dependencies]
cucumber = "0.23.0"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }

